import express from 'express';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import crypto from 'crypto';
import zlib from 'zlib';

const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename);
const app=express(),PORT=process.env.PORT||4173,FPL='https://fantasy.premierleague.com/api',HISTORY_FILE=path.join(__dirname,'data','history.json'),USERS_FILE=path.join(__dirname,'data','users.json'),SESSIONS_FILE=path.join(__dirname,'data','sessions.json'),ACTIVITY_FILE=path.join(__dirname,'data','activity.jsonl');
app.use(express.json({limit:'3mb'}));app.use(express.static(path.join(__dirname,'public')));
const cache=new Map();
async function cachedJson(url,ttl=60000){const hit=cache.get(url);if(hit&&Date.now()-hit.ts<ttl)return hit.data;const r=await fetch(url,{headers:{'User-Agent':'Hisho-FPL-Hub/3.0'}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);const data=await r.json();cache.set(url,{ts:Date.now(),data});return data}
async function cachedText(url,ttl=900000){const key='text:'+url,hit=cache.get(key);if(hit&&Date.now()-hit.ts<ttl)return hit.data;const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 Hisho-FPL-Hub/3.0'}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);const data=await r.text();cache.set(key,{ts:Date.now(),data});return data}
async function cachedAjaxJson(url,ttl=900000){const key='ajax:'+url,hit=cache.get(key);if(hit&&Date.now()-hit.ts<ttl)return hit.data;const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 Hisho-FPL-Hub/4.1','X-Requested-With':'XMLHttpRequest','Accept':'application/json'}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);const data=await r.json();cache.set(key,{ts:Date.now(),data});return data}
const proxy=(fn,ttl=60000)=>async(req,res)=>{try{res.json(await cachedJson(fn(req),ttl))}catch(e){res.status(502).json({error:e.message})}};

function parseCookies(req){const out={};for(const p of String(req.headers.cookie||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return out}
async function readJsonFile(file,fallback){try{return JSON.parse(await fs.readFile(file,'utf8'))}catch{return fallback}}
async function writeJsonFile(file,data){await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,JSON.stringify(data,null,2))}
function passwordHash(password,salt=crypto.randomBytes(16).toString('hex')){const hash=crypto.scryptSync(password,salt,64).toString('hex');return{salt,hash}}
function passwordOk(password,user){try{const a=Buffer.from(passwordHash(password,user.salt).hash,'hex'),b=Buffer.from(user.password_hash,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}}
async function currentUser(req){const sid=parseCookies(req).hisho_sid;if(!sid)return null;const sessions=await readJsonFile(SESSIONS_FILE,{sessions:{}}),sess=sessions.sessions?.[sid];if(!sess||Date.now()>sess.expires){return null}const db=await readJsonFile(USERS_FILE,{users:[]});return db.users.find(u=>u.id===sess.user_id)||null}
async function makeSession(res,user){const db=await readJsonFile(SESSIONS_FILE,{sessions:{}}),sid=crypto.randomBytes(32).toString('hex');db.sessions[sid]={user_id:user.id,created:Date.now(),expires:Date.now()+1000*60*60*24*30};await writeJsonFile(SESSIONS_FILE,db);res.setHeader('Set-Cookie',`hisho_sid=${sid}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000${process.env.NODE_ENV==='production'?'; Secure':''}`)}
function publicUser(u){return u?{id:u.id,email:u.email,name:u.name||'',created_at:u.created_at}:null}
app.post('/api/auth/register',async(req,res)=>{try{const email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||''),name=String(req.body?.name||'').trim().slice(0,80);if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:'Enter a valid email address.'});if(password.length<8)return res.status(400).json({error:'Password must be at least 8 characters.'});const db=await readJsonFile(USERS_FILE,{users:[]});if(db.users.some(u=>u.email===email))return res.status(409).json({error:'An account with this email already exists.'});const ph=passwordHash(password),user={id:crypto.randomUUID(),email,name,salt:ph.salt,password_hash:ph.hash,created_at:new Date().toISOString()};db.users.push(user);await writeJsonFile(USERS_FILE,db);await makeSession(res,user);res.json({user:publicUser(user)})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/auth/login',async(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||'');const db=await readJsonFile(USERS_FILE,{users:[]}),user=db.users.find(u=>u.email===email);if(!user||!passwordOk(password,user))return res.status(401).json({error:'Incorrect email or password.'});await makeSession(res,user);res.json({user:publicUser(user)})});
app.get('/api/auth/me',async(req,res)=>res.json({user:publicUser(await currentUser(req))}));
app.post('/api/auth/logout',async(req,res)=>{const sid=parseCookies(req).hisho_sid,db=await readJsonFile(SESSIONS_FILE,{sessions:{}});if(sid&&db.sessions?.[sid]){delete db.sessions[sid];await writeJsonFile(SESSIONS_FILE,db)}res.setHeader('Set-Cookie','hisho_sid=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0');res.json({ok:true})});
app.post('/api/activity',async(req,res)=>{try{const user=await currentUser(req),event=String(req.body?.event||'').slice(0,80),meta=req.body?.meta&&typeof req.body.meta==='object'?req.body.meta:{};if(!event)return res.status(400).json({error:'event required'});const safeMeta={};for(const [k,v] of Object.entries(meta).slice(0,20)){if(!/password|token|secret|email/i.test(k))safeMeta[String(k).slice(0,50)]=typeof v==='string'?v.slice(0,300):v}await fs.mkdir(path.dirname(ACTIVITY_FILE),{recursive:true});await fs.appendFile(ACTIVITY_FILE,JSON.stringify({ts:new Date().toISOString(),user_id:user?.id||null,event,meta:safeMeta})+'\n');res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/activity',async(req,res)=>{if(!process.env.ADMIN_TOKEN||req.query.token!==process.env.ADMIN_TOKEN)return res.status(403).json({error:'Forbidden'});try{const txt=await fs.readFile(ACTIVITY_FILE,'utf8');res.type('text/plain').send(txt)}catch{res.type('text/plain').send('')}});

const MARKET_BASE='https://pub-e682421888d945d684bcae8890b0ec20.r2.dev/data';
async function cachedGzipCsv(name,ttl=21600000){const key='gzcsv:'+name,hit=cache.get(key);if(hit&&Date.now()-hit.ts<ttl)return hit.data;const r=await fetch(`${MARKET_BASE}/${name}.csv.gz`,{headers:{'User-Agent':'Hisho-FPL-Hub/5.0'}});if(!r.ok)throw new Error(`Market dataset ${r.status}`);const buf=Buffer.from(await r.arrayBuffer()),text=zlib.gunzipSync(buf).toString('utf8'),rows=parseCsv(text);cache.set(key,{ts:Date.now(),data:rows});return rows}
function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(x=>x!==''))rows.push(row);row=[]}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}if(rows.length<2)return[];const h=rows[0];return rows.slice(1).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??''])))}
function clubKey(s=''){return norm(s).replace(/footballclub|afc|fc$/g,'').replace(/and/g,'')}
function isCurrentPlClub(name,teams){const k=clubKey(name);return teams.some(t=>{const a=clubKey(t.name),b=clubKey(t.short_name);return k===a||k===b||a.includes(k)||k.includes(a)})}
app.get('/api/market-data',async(req,res)=>{try{const [bootstrap,transfers,players]=await Promise.all([cachedJson(`${FPL}/bootstrap-static/`,300000),cachedGzipCsv('transfers',21600000),cachedGzipCsv('players',21600000)]),teams=bootstrap.teams||[];const relevant=transfers.filter(t=>{const y=String(t.transfer_season||t.transfer_date||'');return (y.includes('2026')||y.includes('2025'))&&(isCurrentPlClub(t.from_club_name,teams)||isCurrentPlClub(t.to_club_name,teams))}).sort((a,b)=>String(b.transfer_date).localeCompare(String(a.transfer_date))).slice(0,1800);const pool=players.filter(x=>isCurrentPlClub(x.current_club_name,teams)),used=new Set(),images=[];for(const p of bootstrap.elements){let best=null,bs=0;for(const x of pool){if(used.has(x.player_id))continue;const sc=Math.max(similarity(p.web_name,x.name),similarity(`${p.first_name} ${p.second_name}`,x.name));if(sc>bs){bs=sc;best=x}}if(best&&bs>=.80&&best.image_url){used.add(best.player_id);images.push({fpl_id:p.id,image_url:best.image_url,source:'weekly-player-dataset',confidence:+bs.toFixed(2)})}}res.json({updated_at:new Date().toISOString(),source:'dcaribou/transfermarkt-datasets (CC0, weekly refresh)',transfers:relevant,images})}catch(e){res.status(502).json({error:e.message})}});

app.get('/api/fpl/bootstrap',proxy(()=>`${FPL}/bootstrap-static/`,300000));
app.get('/api/fpl/entry/:id',proxy(req=>`${FPL}/entry/${req.params.id}/`,60000));
app.get('/api/fpl/entry/:id/history',proxy(req=>`${FPL}/entry/${req.params.id}/history/`,60000));
app.get('/api/fpl/entry/:id/transfers',proxy(req=>`${FPL}/entry/${req.params.id}/transfers/`,60000));
app.get('/api/fpl/entry/:id/picks/:gw',proxy(req=>`${FPL}/entry/${req.params.id}/event/${req.params.gw}/picks/`,30000));
app.get('/api/fpl/live/:gw',proxy(req=>`${FPL}/event/${req.params.gw}/live/`,30000));
app.get('/api/fpl/fixtures',proxy(req=>`${FPL}/fixtures/${req.query.event?`?event=${encodeURIComponent(req.query.event)}`:''}`,60000));
app.get('/api/fpl/league/:id',proxy(req=>`${FPL}/leagues-classic/${req.params.id}/standings/?page_standings=${req.query.page||1}`,60000));

async function readHistory(){try{return JSON.parse(await fs.readFile(HISTORY_FILE,'utf8'))}catch{return{snapshots:[]}}}
async function writeHistory(data){await fs.mkdir(path.dirname(HISTORY_FILE),{recursive:true});await fs.writeFile(HISTORY_FILE,JSON.stringify(data,null,2))}
app.get('/api/history/:entryId',async(req,res)=>{const db=await readHistory();res.json(db.snapshots.filter(s=>String(s.entryId)===String(req.params.entryId)))});
app.post('/api/snapshot/:entryId',async(req,res)=>{try{const entryId=req.params.entryId,bootstrap=await cachedJson(`${FPL}/bootstrap-static/`,120000),entry=await cachedJson(`${FPL}/entry/${entryId}/`,30000),event=bootstrap.events.find(e=>e.is_current)||bootstrap.events.find(e=>e.is_next)||bootstrap.events[0],gw=event?.id||1;let picks=null,live=null;try{picks=await cachedJson(`${FPL}/entry/${entryId}/event/${gw}/picks/`,30000)}catch{}try{live=await cachedJson(`${FPL}/event/${gw}/live/`,30000)}catch{}const players=bootstrap.elements.map(p=>({...p,price:p.now_cost/10})),snap={ts:new Date().toISOString(),entryId,gw,entry,picks,live,players};const db=await readHistory();db.snapshots.push(snap);await writeHistory(db);res.json({ok:true,snapshot:snap})}catch(e){res.status(500).json({error:e.message})}});

async function mapLimit(items,limit,fn){const out=new Array(items.length);let idx=0;async function worker(){while(idx<items.length){const i=idx++;try{out[i]=await fn(items[i],i)}catch{out[i]=null}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}
app.get('/api/fpl/league/:id/analysis/:gw',async(req,res)=>{try{const leagueId=req.params.id,gw=Number(req.params.gw),limit=Math.min(500,Math.max(10,Number(req.query.limit)||200));let page=1,all=[],league=null,hasNext=true;while(hasNext&&all.length<limit&&page<=20){const d=await cachedJson(`${FPL}/leagues-classic/${leagueId}/standings/?page_standings=${page}`,60000);league=league||d.league;const rows=d.standings?.results||[];all.push(...rows);hasNext=!!d.standings?.has_next;page++}all=all.slice(0,limit);const picks=await mapLimit(all,10,async m=>{const d=await cachedJson(`${FPL}/entry/${m.entry}/event/${gw}/picks/`,30000);return{entry:m.entry,picks:d.picks||[],entry_history:d.entry_history||{}}});const byEntry=new Map(picks.filter(Boolean).map(x=>[x.entry,x]));const managers=all.map(m=>({...m,picks:byEntry.get(m.entry)?.picks||[]}));const exp=new Map();for(const m of managers){for(const pk of m.picks){if(!exp.has(pk.element))exp.set(pk.element,{playerId:pk.element,selected:0,captains:0,effective:0});const x=exp.get(pk.element);x.selected++;if(pk.is_captain)x.captains++;x.effective+=Math.max(1,pk.multiplier||1)}}const n=Math.max(1,managers.length);const exposure=[...exp.values()].map(x=>({...x,selectionPct:x.selected/n*100,captainPct:x.captains/n*100,effectivePct:x.effective/n*100}));res.json({league,managers,exposure,loaded:managers.length,truncated:hasNext})}catch(e){res.status(502).json({error:e.message})}});

function extractEncoded(html,name){const patterns=[new RegExp(`var\\s+${name}\\s*=\\s*JSON\\.parse\\('([^']+)'\\)`),new RegExp(`var\\s+${name}\\s*=\\s*JSON\\.parse\\("([^"]+)"\\)`)];for(const re of patterns){const m=html.match(re);if(!m)continue;let s=m[1];try{return JSON.parse(decodeURIComponent(s.replace(/\\x([0-9A-Fa-f]{2})/g,'%$1')))}catch{}try{return JSON.parse(Buffer.from(s,'base64').toString('utf8'))}catch{}}return null}
function norm(s=''){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'')}
function tokens(s=''){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(Boolean)}
function lev(a,b){if(a===b)return 0;if(!a.length)return b.length;if(!b.length)return a.length;const v=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=v[0];v[0]=i;for(let j=1;j<=b.length;j++){const tmp=v[j];v[j]=Math.min(v[j]+1,v[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=tmp}}return v[b.length]}
function similarity(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;if(a===b)return 1;if(a.includes(b)||b.includes(a))return .93;return 1-lev(a,b)/Math.max(a.length,b.length)}
function shotDistanceM(s){const x=Number(s.X),y=Number(s.Y);if(!Number.isFinite(x)||!Number.isFinite(y))return null;return Math.sqrt(((1-x)*105)**2+((y-.5)*68)**2)}
async function getUnderstatShots(season){
  const key=`understat-${season}`,hit=cache.get(key);if(hit&&Date.now()-hit.ts<1800000)return hit.data;
  let dates=[],source='Understat AJAX';
  try{
    const league=await cachedAjaxJson(`https://understat.com/getLeagueData/EPL/${season}`,1800000);
    dates=Array.isArray(league?.dates)?league.dates:[];
  }catch(ajaxError){
    // Backward-compatible fallback for older Understat page payloads.
    const leagueHtml=await cachedText(`https://understat.com/league/EPL/${season}`,1800000);
    const legacy=extractEncoded(leagueHtml,'datesData');
    dates=Array.isArray(legacy)?legacy:(Array.isArray(legacy?.dates)?legacy.dates:[]);source='Understat legacy fallback';
    if(!dates.length)throw ajaxError;
  }
  const ids=dates.filter(m=>m&&(m.isResult===true||m.isResult===1||m.isResult==='1'||m.is_result===true)).map(m=>String(m.id)).filter(Boolean);
  if(!ids.length){const data={matches:0,shots:[],source};cache.set(key,{ts:Date.now(),data});return data}
  const matches=await mapLimit(ids,6,async id=>{
    try{const d=await cachedAjaxJson(`https://understat.com/getMatchData/${id}`,3600000);return d?.shots||d}
    catch{const legacy=extractEncoded(await cachedText(`https://understat.com/match/${id}`,3600000),'shotsData');return legacy}
  });
  const shots=[];for(const m of matches)if(m)for(const side of ['h','a'])for(const shot of(m[side]||[]))shots.push(shot);
  const data={matches:ids.length,shots,source};cache.set(key,{ts:Date.now(),data});return data
}
function bestFplMatch(name,players){const n=norm(name);let direct=players.find(p=>[p.web_name,`${p.first_name} ${p.second_name}`,p.second_name].some(x=>norm(x)===n));if(direct)return{p:direct,confidence:1};const ts=tokens(name),surname=ts.at(-1)||'';let best=null,bestScore=0;for(const p of players){const names=[p.web_name,`${p.first_name} ${p.second_name}`,p.second_name];let s=Math.max(...names.map(x=>similarity(name,x)));const ps=tokens(`${p.first_name} ${p.second_name}`);if(surname&&ps.includes(surname))s=Math.max(s,.88);if(ts.length>1&&ps.some(x=>ts.includes(x)))s+=.03;if(s>bestScore){bestScore=s;best=p}}return bestScore>=.78?{p:best,confidence:Math.min(1,bestScore)}:null}
app.get('/api/understat/player-shots/:season',async(req,res)=>{try{const season=req.params.season,bootstrap=await cachedJson(`${FPL}/bootstrap-static/`,300000),raw=await getUnderstatShots(season),byPlayer=new Map();for(const s of raw.shots){const key=norm(s.player),d=shotDistanceM(s),xg=Number(s.xG)||0;if(!byPlayer.has(key))byPlayer.set(key,{understat_name:s.player,understat_id:Number(s.player_id)||null,shots:0,shots_on_target:0,goals:0,understat_xg:0,understat_npxg:0,distances:[],close_chances:0,very_close_shots:0,big_xg_missed:0});const a=byPlayer.get(key);a.shots++;a.understat_xg+=xg;if(s.situation!=='Penalty')a.understat_npxg+=xg;if(['SavedShot','Goal'].includes(s.result))a.shots_on_target++;if(s.result==='Goal')a.goals++;if(d!=null){a.distances.push(d);if(d<=8)a.very_close_shots++}if(xg>=.30){a.close_chances++;if(s.result!=='Goal')a.big_xg_missed++}}
const used=new Set(),players=[];for(const a of byPlayer.values()){const m=bestFplMatch(a.understat_name,bootstrap.elements.filter(p=>!used.has(p.id)));if(!m)continue;const p=m.p;used.add(p.id);const avg=a.distances.length?a.distances.reduce((x,y)=>x+y,0)/a.distances.length:null;players.push({fpl_id:p.id,match_confidence:+m.confidence.toFixed(2),...a,distances:undefined,understat_xg:+a.understat_xg.toFixed(3),understat_npxg:+a.understat_npxg.toFixed(3),avg_shot_distance_m:avg?+avg.toFixed(2):null,avg_shot_distance_yd:avg?+(avg*1.09361).toFixed(2):null,xg_per_shot:a.shots?+(a.understat_xg/a.shots).toFixed(3):0,shot_conversion:a.shots?+(a.goals/a.shots*100).toFixed(1):0})}res.json({season,matches:raw.matches,shots:raw.shots.length,matched:players.length,total_fpl:bootstrap.elements.length,source:raw.source||'Understat',players})}catch(e){res.status(502).json({error:e.message,note:'Understat is an unofficial source and its page structure can change.'})}});

function decodeXml(s=''){return s.replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
function tag(item,name){const m=item.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'));return m?decodeXml(m[1].trim()):''}
function cleanDesc(s=''){return s.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim().slice(0,240)}
app.get('/api/news',async(req,res)=>{try{const q=String(req.query.q||'Premier League').slice(0,120),url=`https://news.google.com/rss/search?q=${encodeURIComponent(q+' Premier League')}&hl=en-GB&gl=GB&ceid=GB:en`,xml=await cachedText(url,300000),items=[...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].slice(0,18).map(m=>{const x=m[1],title=tag(x,'title'),link=tag(x,'link'),pub=tag(x,'pubDate'),source=tag(x,'source'),description=cleanDesc(tag(x,'description'));return{title:title.replace(/\s+-\s+[^-]+$/,''),link,source,description,when:pub?new Date(pub).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):''}});res.json({query:q,items})}catch(e){res.status(502).json({error:e.message})}});

app.get('/health',(_req,res)=>res.json({ok:true,app:'Hisho FPL Hub'}));
app.listen(PORT,'0.0.0.0',()=>console.log(`Hisho FPL Hub: http://localhost:${PORT}`));
